spring:
  application:
    name: tilab
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: ${SERVER_PORT}

jwt:
  signerKey: ${SIGNER_KEY}

app:
  url: ${URL_SERVER}
  image:
    url: ${IMG_URL}
  admin:
    username: ${USERNAME_ADMIN}
    password: ${PASSWORD_ADMIN}
  qr: ${QR_PAYMENT}
  api:
    webhook: ${SEPAY_WEBHOOK_API}
  staff-refresh-duration: ${STAFF_REFRESH_DURATION}
  customer-refresh-duration: ${CUSTOMER_REFRESH_DURATION}
  access-duration: ${ACCESS_DURATION}
  google:
    jwt-uri: ${GOOGLE_JWT_URI}
    issuer: ${GOOGLE_ISSUER}
  raw-pass: ${DEFAULT_RAW_PASSWORD}